spring:
  datasource:
    teststage:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      initialize: true #指定初始化数据源，是否用data.sql来初始化，默认: true
      name: qianjin
      url: jdbc:mysql://10.10.163.2:3306/test_qianjin_user_center?useUnicode=true&characterEncoding=utf8&useSSL=false
      username: qianjin20160304
      password: qianjin20160304
      validationQuery: select 1

#  profiles:
#    active: @profileActive@
  aop:
    proxy-target-class: true

  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path: classpath:/templates/report

